AWSTemplateFormatVersion: 2010-09-09
Description: Infra for Covid Monitoring
Resources: 
  secGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09e67e426f25ce0d7
      InstanceType: t2.micro
      SecurityGroupIds:
        - !GetAtt [ secGroup, GroupId ]
      KeyName: ec2kp
      UserData: !Base64 |
        #!/bin/bash -ex
        sudo apt update
        sudo apt upgrade -y
        


Outputs:
  ec2PublicDNS:
    Description: Public DNS of EC2 instance
    Value: !GetAtt [myEC2Instance, PublicDnsName]
    Export: 
      Name: ec2PublicDNS